[build-system]
requires = ['setuptools', 'wheel', 'scikit-build', 'cmake', 'ninja', 'requests', 'dune-fem<=2.8.0.dev20201219', 'dune-alugrid<=2.8.0.dev20201219']
build-backend = 'setuptools.build_meta'
